---
name: weatherappwithbloc
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  geolocator: ^5.3.1
  http: ^0.12.0+4
  flutter_spinkit: ^4.1.2+1
  equatable: ^1.2.2
  flutter_bloc: ^5.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
  - images/
